"""add demand status change history

Revision ID: 2b63eb2418ad
Revises: 44b4eb1382db
Create Date: 2026-08-05 02:15:47.074929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b63eb2418ad'
down_revision: Union[str, Sequence[str], None] = '44b4eb1382db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand_status_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='demand_status', native_enum=False, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='demand_status', native_enum=False, length=20), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demand_status_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_status_changes_demand_id'), ['demand_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_status_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_status_changes_demand_id'))

    op.drop_table('demand_status_changes')
    # ### end Alembic commands ###
