"""create demands table

Revision ID: 44b4eb1382db
Revises: 
Create Date: 2026-08-04 23:45:24.535127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '44b4eb1382db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('requester', sa.String(length=80), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='demand_status', native_enum=False, length=20), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('impact BETWEEN 1 AND 5', name='ck_demands_impact_range'),
    sa.CheckConstraint('urgency BETWEEN 1 AND 5', name='ck_demands_urgency_range'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.create_index('ix_demands_priority_score_created_at', ['priority_score', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_demands_requester'), ['requester'], unique=False)
        batch_op.create_index(batch_op.f('ix_demands_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demands_status'))
        batch_op.drop_index(batch_op.f('ix_demands_requester'))
        batch_op.drop_index('ix_demands_priority_score_created_at')

    op.drop_table('demands')
    # ### end Alembic commands ###
